/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import { Platform } from 'react-native';

export const LightTheme = {
  colors: {
    text: '#0a0a0a',
    textSecondary: '#717182',
    textMuted: '#717182',
    textSubtle: '#a1a1a1',
    background: '#ffffff',
    surface: '#ffffff',
    surfaceMuted: '#ececf0',
    border: 'rgba(0, 0, 0, 0.1)',
    hairline: '#e9ebef',
    tint: '#2563eb',
    icon: '#2563eb',
    tabIconDefault: '#a1a1a1',
    tabIconSelected: '#2563eb',
    primary: '#2563eb',
    primaryMuted: '#dbeafe',
    primaryForeground: '#ffffff',
    primarySoftText: '#93c5fd',
    success: '#16a34a',
    successBackground: '#ecfdf5',
    info: '#4f46e5',
    infoBackground: '#eef2ff',
    warning: '#b45309',
    warningBackground: '#fff7ed',
    danger: '#d4183d',
    dangerBackground: '#fee2e2',
    pillBackground: '#2563eb',
    pillForeground: '#ffffff',
    chipBorder: 'rgba(0, 0, 0, 0.1)',
    chipBackground: '#ffffff',
    chipActiveBackground: '#dbeafe',
    chipActiveText: '#2563eb',
    shadow: 'rgba(2, 6, 23, 0.08)',
    overlay: 'rgba(15, 23, 42, 0.05)',
    navigationBackground: '#ffffff',
    navigationBorder: 'rgba(0, 0, 0, 0.1)',
    inputBackground: '#f3f3f5',
    inputPlaceholder: '#717182',
    warningBackgroundSoft: '#fff7ed',
    warningSoftText: '#b45309',
  },
};

export const DarkTheme = {
  colors: {
    text: '#fafafa',
    textSecondary: '#a1a1a1',
    textMuted: '#a1a1a1',
    textSubtle: '#525252',
    background: '#0a0a0a',
    surface: '#141414',
    surfaceMuted: '#1f1f1f',
    border: '#262626',
    hairline: '#262626',
    tint: '#fafafa',
    icon: '#fafafa',
    tabIconDefault: '#a1a1a1',
    tabIconSelected: '#fafafa',
    primary: '#fafafa',
    primaryMuted: '#262626',
    primaryForeground: '#171717',
    primarySoftText: '#a1a1a1',
    success: '#22c55e',
    successBackground: '#0f1f16',
    info: '#818cf8',
    infoBackground: '#1e1b4b',
    warning: '#f59e0b',
    warningBackground: '#2a1a07',
    danger: '#82181a',
    dangerBackground: '#3a0f11',
    pillBackground: '#fafafa',
    pillForeground: '#171717',
    chipBorder: '#262626',
    chipBackground: '#0a0a0a',
    chipActiveBackground: '#262626',
    chipActiveText: '#fafafa',
    shadow: 'rgba(0, 0, 0, 0.4)',
    overlay: 'rgba(0, 0, 0, 0.4)',
    navigationBackground: '#0a0a0a',
    navigationBorder: '#262626',
    inputBackground: '#262626',
    inputPlaceholder: '#a1a1a1',
    warningBackgroundSoft: '#2a1a07',
    warningSoftText: '#f59e0b',
  },
};

export const NeonTheme = {
  colors: {
    text: '#f6e6ff',
    textSecondary: '#d7b8ff',
    textMuted: '#b98bff',
    textSubtle: '#8a5bff',
    background: '#0a0416',
    surface: '#14072a',
    surfaceMuted: '#1d0a3a',
    border: '#2c0f58',
    hairline: '#2c0f58',
    tint: '#b100ff',
    icon: '#b100ff',
    tabIconDefault: '#8a5bff',
    tabIconSelected: '#b100ff',
    primary: '#b100ff',
    primaryMuted: '#6f00ff',
    primaryForeground: '#0a0416',
    primarySoftText: '#d7b8ff',
    success: '#6b00ff',
    successBackground: '#14072a',
    info: '#8a5bff',
    infoBackground: '#14072a',
    warning: '#a855f7',
    warningBackground: '#1d0a3a',
    danger: '#ff2d9a',
    dangerBackground: '#2a0b2f',
    pillBackground: '#b100ff',
    pillForeground: '#0a0416',
    chipBorder: '#2c0f58',
    chipBackground: '#14072a',
    chipActiveBackground: '#2c0f58',
    chipActiveText: '#f6e6ff',
    shadow: 'rgba(10, 4, 22, 0.7)',
    overlay: 'rgba(10, 4, 22, 0.5)',
    navigationBackground: '#0a0416',
    navigationBorder: '#2c0f58',
    inputBackground: '#1d0a3a',
    inputPlaceholder: '#b98bff',
    warningBackgroundSoft: '#1d0a3a',
    warningSoftText: '#f6e6ff',
  },
};

export const CoffeeTheme = {
  colors: {
    text: '#2f1b12',
    textSecondary: '#5a3a2a',
    textMuted: '#7f5539',
    textSubtle: '#a07a5a',
    background: '#e2d3c5',
    surface: '#d4bfae',
    surfaceMuted: '#c3a78f',
    border: '#b18f75',
    hairline: '#b18f75',
    tint: '#7f5539',
    icon: '#7f5539',
    tabIconDefault: '#a07a5a',
    tabIconSelected: '#7f5539',
    primary: '#7f5539',
    primaryMuted: '#a17455',
    primaryForeground: '#ffffff',
    primarySoftText: '#5a3a2a',
    success: '#7f5539',
    successBackground: '#d4bfae',
    info: '#a07a5a',
    infoBackground: '#d4bfae',
    warning: '#c79a7a',
    warningBackground: '#d4bfae',
    danger: '#a15c3a',
    dangerBackground: '#d0b29f',
    pillBackground: '#7f5539',
    pillForeground: '#ffffff',
    chipBorder: '#b18f75',
    chipBackground: '#d4bfae',
    chipActiveBackground: '#a17455',
    chipActiveText: '#2f1b12',
    shadow: 'rgba(127, 85, 57, 0.25)',
    overlay: 'rgba(47, 27, 18, 0.08)',
    navigationBackground: '#e2d3c5',
    navigationBorder: '#b18f75',
    inputBackground: '#c3a78f',
    inputPlaceholder: '#7f5539',
    warningBackgroundSoft: '#d4bfae',
    warningSoftText: '#5a3a2a',
  },
};

export const TestTheme = {
  colors: {
    text: '#ffffff',
    textSecondary: '#f1d7e4',
    textMuted: '#d9b8cb',
    textSubtle: '#b89ab1',
    background: '#5c4d7d',
    surface: '#723c70',
    surfaceMuted: '#892b64',
    border: '#455e89',
    hairline: '#455e89',
    tint: '#b7094c',
    icon: '#b7094c',
    tabIconDefault: '#d9b8cb',
    tabIconSelected: '#b7094c',
    primary: '#b7094c',
    primaryMuted: '#a01a58',
    primaryForeground: '#ffffff',
    primarySoftText: '#f1d7e4',
    success: '#0091ad',
    successBackground: '#2e6f95',
    info: '#1780a1',
    infoBackground: '#2e6f95',
    warning: '#892b64',
    warningBackground: '#723c70',
    danger: '#a01a58',
    dangerBackground: '#723c70',
    pillBackground: '#b7094c',
    pillForeground: '#ffffff',
    chipBorder: '#455e89',
    chipBackground: '#723c70',
    chipActiveBackground: '#892b64',
    chipActiveText: '#ffffff',
    shadow: 'rgba(27, 9, 22, 0.6)',
    overlay: 'rgba(27, 9, 22, 0.45)',
    navigationBackground: '#5c4d7d',
    navigationBorder: '#455e89',
    inputBackground: '#723c70',
    inputPlaceholder: '#d9b8cb',
    warningBackgroundSoft: '#723c70',
    warningSoftText: '#f1d7e4',
  },
};

export type ThemeColors = typeof LightTheme.colors;

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
