import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    backgroundColor: "#0f448f",
  },
  decorativeIcon: {
    position: "absolute",
  },
  dotGrid: {
    position: "absolute",
    width: 64,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255, 255, 255, 0.26)",
  },
  accentMark: {
    position: "absolute",
    color: "rgba(255, 255, 255, 0.22)",
    fontSize: 36,
    fontWeight: "200",
    letterSpacing: 0,
  },
  circleMark: {
    position: "absolute",
    width: 18,
    height: 18,
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.18)",
    borderRadius: 9,
  },
  brand: {
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: 216,
    height: 216,
    borderRadius: 108,
  },
  title: {
    marginTop: 4,
    color: "#ffffff",
    fontSize: 58,
    fontWeight: "800",
    letterSpacing: 0,
  },
  taglineRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  taglineLine: {
    width: 38,
    height: 2,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
  },
  tagline: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "600",
    letterSpacing: 0,
  },
  loading: {
    position: "absolute",
    bottom: "16%",
    alignItems: "center",
  },
  spinner: {
    width: 68,
    height: 68,
    alignItems: "center",
    justifyContent: "center",
  },
  spinnerTrack: {
    position: "absolute",
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 7,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  spinnerArc: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 7,
    borderRightColor: "transparent",
    borderBottomColor: "transparent",
  },
  loadingText: {
    marginTop: 18,
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "500",
    letterSpacing: 0,
  },
});
