import { StyleSheet } from "react-native";
import { type ThemeColors } from "@/constants/theme";

export const createSettingsStyles = (theme: ThemeColors) =>
  StyleSheet.create({
    card: {
      borderRadius: 18,
      backgroundColor: theme.surface,
      padding: 20,
      gap: 12,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadow,
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
    loadingRow: { paddingVertical: 20, alignItems: "center" as const },
    heading: { fontSize: 20, fontWeight: "700" as const, color: theme.text },
    body: { fontSize: 15, color: theme.textSecondary, lineHeight: 22 },
    formGroup: { gap: 6 },
    label: { fontSize: 14, fontWeight: "600" as const, color: theme.text },
    input: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: theme.text,
      backgroundColor: theme.background,
    },
    inputDisabled: { backgroundColor: theme.surfaceMuted, color: theme.textMuted },
    textarea: { minHeight: 90, textAlignVertical: "top" as const },
    errorText: { color: theme.danger, fontSize: 12 },
    successText: { color: theme.success, fontSize: 13, fontWeight: "700" as const },
    helperText: { fontSize: 12, color: theme.textMuted },
    primaryButton: {
      marginTop: 8,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: theme.primary,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: "center" as const,
    },
    primaryButtonLabel: { color: theme.primaryForeground, fontSize: 15, fontWeight: "700" as const },
    deleteButton: { backgroundColor: theme.danger, borderColor: theme.danger },
    secondaryButton: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, borderWidth: 1, borderColor: theme.border },
    secondaryButtonLabel: { color: theme.text, fontWeight: "600" as const },
    buttonDisabled: { opacity: 0.6 },
    comingSoon: { fontSize: 12, color: theme.textMuted },
    comingSoonCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceMuted,
      padding: 14,
      gap: 6,
    },
    comingSoonTitle: { fontSize: 15, fontWeight: "700" as const, color: theme.text },
    comingSoonBody: { fontSize: 13, color: theme.textMuted },
    comingSoonBadge: {
      alignSelf: "flex-start" as const,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceMuted,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    comingSoonBadgeText: { fontSize: 11, fontWeight: "700" as const, color: theme.textMuted },
    dangerZone: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.danger,
      backgroundColor: theme.dangerBackground,
      padding: 16,
      gap: 12,
    },
    dangerTitle: { fontSize: 16, fontWeight: "700" as const, color: theme.danger },
    avatarRow: { flexDirection: "row" as const, alignItems: "center" as const, gap: 14 },
    avatarCircle: { width: 64, height: 64, borderRadius: 32, backgroundColor: theme.surfaceMuted, alignItems: "center" as const, justifyContent: "center" as const },
    avatarLabel: { fontSize: 20, fontWeight: "700" as const, color: theme.text },
    avatarImage: { width: 64, height: 64, borderRadius: 32 },
  });
