import { I18nManager, StyleSheet } from "react-native";
import {
  MarketplaceRadius,
  MarketplaceShadow,
  MarketplaceSpacing,
  MarketplaceTypography,
  type ThemeColors,
} from "@/constants/theme";

export const createSettingsStyles = (theme: ThemeColors) =>
  StyleSheet.create({
    card: {
      borderRadius: MarketplaceRadius.card,
      backgroundColor: theme.surface,
      padding: MarketplaceSpacing.xl,
      gap: MarketplaceSpacing.md,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadow,
      ...MarketplaceShadow.card,
    },
    loadingRow: { paddingVertical: MarketplaceSpacing.xl, alignItems: "center" as const },
    heading: { fontSize: MarketplaceTypography.title, fontWeight: "700" as const, color: theme.text },
    body: { fontSize: MarketplaceTypography.body, color: theme.textSecondary, lineHeight: 21 },
    formGroup: { gap: MarketplaceSpacing.sm },
    label: { fontSize: MarketplaceTypography.body, fontWeight: "700" as const, color: theme.text },
    input: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: MarketplaceRadius.md,
      paddingHorizontal: MarketplaceSpacing.md,
      paddingVertical: MarketplaceSpacing.md,
      color: theme.text,
      backgroundColor: theme.inputBackground,
      textAlign: I18nManager.isRTL ? "right" : "left",
    },
    passwordInputRow: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: MarketplaceRadius.md,
      paddingLeft: MarketplaceSpacing.md,
      paddingRight: MarketplaceSpacing.sm,
      backgroundColor: theme.inputBackground,
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: MarketplaceSpacing.sm,
    },
    passwordInput: {
      flex: 1,
      minHeight: 44,
      paddingVertical: MarketplaceSpacing.md,
      color: theme.text,
      fontSize: MarketplaceTypography.input,
      textAlign: I18nManager.isRTL ? "right" : "left",
    },
    passwordVisibilityButton: {
      width: 36,
      height: 36,
      borderRadius: MarketplaceRadius.pill,
      alignItems: "center" as const,
      justifyContent: "center" as const,
    },
    inputDisabled: { backgroundColor: theme.surfaceMuted, color: theme.textMuted },
    textarea: { minHeight: 90, textAlignVertical: "top" as const },
    errorText: { color: theme.danger, fontSize: MarketplaceTypography.meta },
    successText: { color: theme.success, fontSize: MarketplaceTypography.bodySmall, fontWeight: "700" as const },
    helperText: { fontSize: MarketplaceTypography.meta, color: theme.textMuted },
    primaryButton: {
      marginTop: MarketplaceSpacing.sm,
      paddingVertical: MarketplaceSpacing.md,
      borderRadius: MarketplaceRadius.lg,
      backgroundColor: theme.primary,
      borderWidth: 1,
      borderColor: theme.primary,
      alignItems: "center" as const,
    },
    primaryButtonLabel: { color: theme.primaryForeground, fontSize: MarketplaceTypography.input, fontWeight: "700" as const },
    deleteButton: { backgroundColor: theme.danger, borderColor: theme.danger },
    secondaryButton: {
      paddingHorizontal: MarketplaceSpacing.md,
      paddingVertical: MarketplaceSpacing.md,
      borderRadius: MarketplaceRadius.md,
      borderWidth: 1,
      borderColor: theme.border,
    },
    secondaryButtonLabel: { color: theme.text, fontWeight: "600" as const },
    buttonDisabled: { opacity: 0.6 },
    comingSoon: { fontSize: MarketplaceTypography.meta, color: theme.textMuted },
    comingSoonCard: {
      borderRadius: MarketplaceRadius.md,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceMuted,
      padding: MarketplaceSpacing.lg,
      gap: MarketplaceSpacing.sm,
    },
    comingSoonTitle: { fontSize: MarketplaceTypography.input, fontWeight: "700" as const, color: theme.text },
    comingSoonBody: { fontSize: MarketplaceTypography.bodySmall, color: theme.textMuted, lineHeight: 19 },
    comingSoonBadge: {
      alignSelf: "flex-start" as const,
      borderRadius: MarketplaceRadius.pill,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceMuted,
      paddingHorizontal: MarketplaceSpacing.md,
      paddingVertical: MarketplaceSpacing.xs,
    },
    comingSoonBadgeText: { fontSize: MarketplaceTypography.caption, fontWeight: "700" as const, color: theme.textMuted },
    dangerZone: {
      borderRadius: MarketplaceRadius.lg,
      borderWidth: 1,
      borderColor: theme.danger,
      backgroundColor: theme.dangerBackground,
      padding: MarketplaceSpacing.lg,
      gap: MarketplaceSpacing.md,
    },
    dangerTitle: { fontSize: MarketplaceTypography.input, fontWeight: "700" as const, color: theme.danger },
    avatarRow: { flexDirection: "row" as const, alignItems: "center" as const, gap: MarketplaceSpacing.lg },
    avatarCircle: {
      width: 64,
      height: 64,
      borderRadius: MarketplaceRadius.pill,
      backgroundColor: theme.surfaceMuted,
      alignItems: "center" as const,
      justifyContent: "center" as const,
    },
    avatarLabel: { fontSize: MarketplaceTypography.title, fontWeight: "700" as const, color: theme.text },
    avatarImage: { width: 64, height: 64, borderRadius: 32 },
  });
